import { EstadoIncidente, NivelSeveridad } from "@safecampus/shared-types";

import type {
  OperatorLoad,
  WhatsAppConversation,
  WhatsAppQuickReply,
} from "./types";

const now = "2026-05-08T15:40:00Z";

export const whatsappQuickReplies: WhatsAppQuickReply[] = [
  {
    id: "ack-1",
    label: "Recepcion de alerta",
    text: "Hemos recibido tu alerta. Un operador de SafeCampus esta revisando el caso ahora mismo.",
  },
  {
    id: "loc-1",
    label: "Confirmar ubicacion",
    text: "Por favor, comparte tu ubicacion exacta o el punto de referencia mas cercano dentro del campus.",
  },
  {
    id: "safe-1",
    label: "Mantente a salvo",
    text: "Mantente en una zona segura y evita acercarte nuevamente al punto del incidente mientras llega apoyo.",
  },
  {
    id: "close-1",
    label: "Cierre de caso",
    text: "Gracias por la informacion. Daremos seguimiento interno y te avisaremos si necesitamos mas datos.",
  },
];

export const whatsappOperators = [
  "Jorge Salinas",
  "Rosa Quispe",
  "Marco Diaz",
  "Lucia Navarro",
];

export const whatsappOperatorLoad: OperatorLoad[] = [
  { name: "Jorge Salinas", activeChats: 4, waitingChats: 1, escalatedCases: 2 },
  { name: "Rosa Quispe", activeChats: 5, waitingChats: 0, escalatedCases: 3 },
  { name: "Marco Diaz", activeChats: 2, waitingChats: 2, escalatedCases: 1 },
  { name: "Lucia Navarro", activeChats: 3, waitingChats: 1, escalatedCases: 2 },
];

export const whatsappConversationsMock: WhatsAppConversation[] = [
  {
    id: "wa-001",
    waConversationId: "wamid.conversation.001",
    contactName: "Andrea Paredes",
    phone: "+51 987 111 203",
    queue: "esperando",
    unreadCount: 3,
    priority: NivelSeveridad.ALTO,
    assignedOperator: null,
    intent: "persona_sospechosa",
    botConfidence: 0.89,
    sentimentScore: 2.4,
    firstResponseSeconds: 38,
    satisfactionScore: null,
    needsHumanHandoff: true,
    containsIncidentSignal: true,
    slaBreached: false,
    resolvedBy: null,
    lastMessage: "Hay una persona rondando carros en el estacionamiento central.",
    lastActivityAt: now,
    aiSummary:
      "La usuaria reporta presencia sospechosa en estacionamiento principal. Riesgo potencial de hurto. Se recomienda takeover humano y patrullaje inmediato.",
    recommendedPlaybook: "Verificar ubicacion, levantar incidente y despachar operador de ronda.",
    tags: ["riesgo", "estacionamiento", "whatsapp"],
    linkedIncident: {
      id: "inc-001",
      codigo: "INC-20260508-0142",
      titulo: "Persona sospechosa en estacionamiento principal",
      estado: EstadoIncidente.EN_ATENCION,
      severidad: NivelSeveridad.ALTO,
      zona: "Estacionamiento principal",
    },
    messages: [
      {
        id: "m-001-1",
        author: "usuario",
        text: "Hola, hay una persona extraña viendo los autos en el estacionamiento central.",
        createdAt: "2026-05-08T15:34:00Z",
        delivery: "read",
      },
      {
        id: "m-001-2",
        author: "bot",
        text: "Gracias por alertarnos. ¿Puedes indicar si la persona sigue en el lugar y cerca de que acceso se encuentra?",
        createdAt: "2026-05-08T15:34:20Z",
        delivery: "read",
      },
      {
        id: "m-001-3",
        author: "usuario",
        text: "Si, sigue cerca del acceso vehicular A.",
        createdAt: "2026-05-08T15:35:05Z",
        delivery: "read",
      },
      {
        id: "m-001-4",
        author: "sistema",
        text: "El bot marco la conversacion para takeover humano por riesgo alto.",
        createdAt: "2026-05-08T15:35:20Z",
        delivery: "read",
      },
      {
        id: "m-001-5",
        author: "usuario",
        text: "Ahora esta caminando entre los carros de la fila 3.",
        createdAt: "2026-05-08T15:39:50Z",
        delivery: "delivered",
      },
    ],
  },
  {
    id: "wa-002",
    waConversationId: "wamid.conversation.002",
    contactName: "Daniel Torres",
    phone: "+51 956 882 014",
    queue: "humano",
    unreadCount: 0,
    priority: NivelSeveridad.CRITICO,
    assignedOperator: "Rosa Quispe",
    intent: "emergencia_medica",
    botConfidence: 0.96,
    sentimentScore: 1.8,
    firstResponseSeconds: 21,
    satisfactionScore: null,
    needsHumanHandoff: true,
    containsIncidentSignal: true,
    slaBreached: false,
    resolvedBy: null,
    lastMessage: "Ya esta llegando la brigada, gracias.",
    lastActivityAt: "2026-05-08T15:31:00Z",
    aiSummary:
      "Caso de emergencia medica con desmayo reportado. Conversacion priorizada y derivada a operadora. Incidente ya vinculado.",
    recommendedPlaybook: "Mantener contacto hasta confirmar atencion presencial.",
    tags: ["medico", "critico", "derivado"],
    linkedIncident: {
      id: "inc-002",
      codigo: "INC-20260508-0140",
      titulo: "Desmayo en Patio de Letras",
      estado: EstadoIncidente.EN_ATENCION,
      severidad: NivelSeveridad.CRITICO,
      zona: "Patio de Letras",
    },
    messages: [
      {
        id: "m-002-1",
        author: "usuario",
        text: "Una estudiante se desmayo en Patio de Letras.",
        createdAt: "2026-05-08T15:10:00Z",
        delivery: "read",
      },
      {
        id: "m-002-2",
        author: "bot",
        text: "Estoy escalando esto de inmediato. Mantente cerca y dime si la persona respira normalmente.",
        createdAt: "2026-05-08T15:10:18Z",
        delivery: "read",
      },
      {
        id: "m-002-3",
        author: "operador",
        text: "Soy Rosa de SafeCampus. La brigada ya fue despachada al Patio de Letras. ¿Siguen junto a la estudiante?",
        createdAt: "2026-05-08T15:11:02Z",
        delivery: "read",
      },
      {
        id: "m-002-4",
        author: "usuario",
        text: "Si, seguimos con ella. Ya esta reaccionando.",
        createdAt: "2026-05-08T15:12:10Z",
        delivery: "read",
      },
      {
        id: "m-002-5",
        author: "usuario",
        text: "Ya esta llegando la brigada, gracias.",
        createdAt: "2026-05-08T15:31:00Z",
        delivery: "delivered",
      },
    ],
  },
  {
    id: "wa-003",
    waConversationId: "wamid.conversation.003",
    contactName: "Mesa PUCP",
    phone: "+51 944 345 100",
    queue: "bot",
    unreadCount: 1,
    priority: NivelSeveridad.BAJO,
    assignedOperator: null,
    intent: "horario_atencion",
    botConfidence: 0.97,
    sentimentScore: 4.5,
    firstResponseSeconds: 12,
    satisfactionScore: 4.7,
    needsHumanHandoff: false,
    containsIncidentSignal: false,
    slaBreached: false,
    resolvedBy: "bot",
    lastMessage: "Gracias, eso era todo.",
    lastActivityAt: "2026-05-08T14:44:00Z",
    aiSummary:
      "Consulta informativa resuelta automaticamente sin escalamiento.",
    recommendedPlaybook: "No requiere accion humana.",
    tags: ["faq", "resuelto_por_bot"],
    linkedIncident: null,
    messages: [
      {
        id: "m-003-1",
        author: "usuario",
        text: "¿Hasta que hora atiende oficina de objetos perdidos?",
        createdAt: "2026-05-08T14:42:00Z",
        delivery: "read",
      },
      {
        id: "m-003-2",
        author: "bot",
        text: "El modulo de objetos perdidos atiende de lunes a viernes de 8:00 a 18:00.",
        createdAt: "2026-05-08T14:42:12Z",
        delivery: "read",
      },
      {
        id: "m-003-3",
        author: "usuario",
        text: "Gracias, eso era todo.",
        createdAt: "2026-05-08T14:44:00Z",
        delivery: "read",
      },
    ],
  },
  {
    id: "wa-004",
    waConversationId: "wamid.conversation.004",
    contactName: "Patricia Ramos",
    phone: "+51 932 444 222",
    queue: "humano",
    unreadCount: 2,
    priority: NivelSeveridad.MEDIO,
    assignedOperator: "Jorge Salinas",
    intent: "robo",
    botConfidence: 0.78,
    sentimentScore: 2.1,
    firstResponseSeconds: 65,
    satisfactionScore: 3.2,
    needsHumanHandoff: true,
    containsIncidentSignal: true,
    slaBreached: true,
    resolvedBy: null,
    lastMessage: "Me quitaron la mochila cerca del pabellon H.",
    lastActivityAt: "2026-05-08T15:07:00Z",
    aiSummary:
      "Reporte de posible hurto con necesidad de precision de ubicacion y toma de datos para incidente.",
    recommendedPlaybook: "Recabar descripcion del sospechoso y direccion de escape. Priorizar patrullaje.",
    tags: ["hurto", "pabellon_h", "sla_alerta"],
    linkedIncident: {
      id: "inc-003",
      codigo: "INC-20260508-0137",
      titulo: "Posible robo de mochila en Pabellon H",
      estado: EstadoIncidente.EN_EVALUACION,
      severidad: NivelSeveridad.MEDIO,
      zona: "Pabellon H",
    },
    messages: [
      {
        id: "m-004-1",
        author: "usuario",
        text: "Me quitaron la mochila cerca del pabellon H.",
        createdAt: "2026-05-08T15:05:00Z",
        delivery: "read",
      },
      {
        id: "m-004-2",
        author: "bot",
        text: "Voy a pedir apoyo. ¿En que piso o acceso ocurrio?",
        createdAt: "2026-05-08T15:05:20Z",
        delivery: "read",
      },
      {
        id: "m-004-3",
        author: "usuario",
        text: "En la salida lateral del primer piso.",
        createdAt: "2026-05-08T15:06:40Z",
        delivery: "delivered",
      },
    ],
  },
  {
    id: "wa-005",
    waConversationId: "wamid.conversation.005",
    contactName: "Carlos Mendoza",
    phone: "+51 998 310 410",
    queue: "cerrado",
    unreadCount: 0,
    priority: NivelSeveridad.BAJO,
    assignedOperator: "Lucia Navarro",
    intent: "objeto_perdido",
    botConfidence: 0.83,
    sentimentScore: 4.2,
    firstResponseSeconds: 44,
    satisfactionScore: 4.4,
    needsHumanHandoff: true,
    containsIncidentSignal: false,
    slaBreached: false,
    resolvedBy: "humano",
    lastMessage: "Perfecto, pasare a recogerlo. Muchas gracias.",
    lastActivityAt: "2026-05-08T11:15:00Z",
    aiSummary:
      "Caso cerrado por operadora luego de validar coincidencia con objeto encontrado.",
    recommendedPlaybook: "Sin acciones adicionales.",
    tags: ["lost-found", "cerrado"],
    linkedIncident: null,
    messages: [
      {
        id: "m-005-1",
        author: "usuario",
        text: "Creo que perdi mi carnet cerca de cafeteria.",
        createdAt: "2026-05-08T10:40:00Z",
        delivery: "read",
      },
      {
        id: "m-005-2",
        author: "operador",
        text: "Encontramos un carnet con tus datos. Puedes acercarte al modulo central con tu DNI.",
        createdAt: "2026-05-08T11:10:00Z",
        delivery: "read",
      },
      {
        id: "m-005-3",
        author: "usuario",
        text: "Perfecto, pasare a recogerlo. Muchas gracias.",
        createdAt: "2026-05-08T11:15:00Z",
        delivery: "read",
      },
    ],
  },
  {
    id: "wa-006",
    waConversationId: "wamid.conversation.006",
    contactName: "Sensor B-17",
    phone: "+51 900 000 017",
    queue: "bot",
    unreadCount: 0,
    priority: NivelSeveridad.CRITICO,
    assignedOperator: null,
    intent: "alerta_iot",
    botConfidence: 0.91,
    sentimentScore: 3.0,
    firstResponseSeconds: 14,
    satisfactionScore: null,
    needsHumanHandoff: true,
    containsIncidentSignal: true,
    slaBreached: false,
    resolvedBy: null,
    lastMessage: "Alerta automatica validada, esperando confirmacion humana.",
    lastActivityAt: "2026-05-08T15:18:00Z",
    aiSummary:
      "Disparo automatizado desde canal de mensajeria para validar con operador una alarma de humo.",
    recommendedPlaybook: "Corroborar en campo y decidir escalamiento a incendio.",
    tags: ["iot", "humo", "validacion"],
    linkedIncident: {
      id: "inc-004",
      codigo: "INC-20260508-0139",
      titulo: "Alerta de humo en cafetería central",
      estado: EstadoIncidente.EN_EVALUACION,
      severidad: NivelSeveridad.CRITICO,
      zona: "Cafeteria Central",
    },
    messages: [
      {
        id: "m-006-1",
        author: "sistema",
        text: "Se detecto alerta automatica de humo en Cafeteria Central.",
        createdAt: "2026-05-08T15:17:30Z",
        delivery: "read",
      },
      {
        id: "m-006-2",
        author: "bot",
        text: "Alerta automatica validada, esperando confirmacion humana.",
        createdAt: "2026-05-08T15:18:00Z",
        delivery: "read",
      },
    ],
  },
];